//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppFastReport.EntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO
    {
        public int id { get; set; }
        public int id_categoria { get; set; }
        public string descricao { get; set; }
        public decimal valor { get; set; }
        public int qtd { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
    }
}
